apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-app
  labels:
    app: guestbook-app
    provider: guestbook
    heritage: helm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook-app
        provider: guestbook
        heritage: helm
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
