apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    provider: guestbook
    heritage: helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: guestbook
