apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
    provider: redis
    heritage: helm
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-master
