apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis-slave
    provider: redis
    heritage: helm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-slave
        provider: redis
        heritage: helm
    spec:
      containers:
      - name: worker
        image: gcr.io/google_samples/gb-redisslave:v1
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
